version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - backend/.env.example
    ports:
      - "8010:8010"
    volumes:
      - ./backend:/app/backend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8010
    ports:
      - "3010:3010"
    volumes:
      - ./frontend:/app