FROM node:18-alpine
WORKDIR /app
COPY frontend/package.json frontend/yarn.lock* ./
RUN yarn install --frozen-lockfile || yarn install
COPY frontend /app
ENV NEXT_PUBLIC_BACKEND_URL=http://localhost:8010
EXPOSE 3010
CMD ["yarn", "dev", "-p", "3010"]